server.port=8080

# Kafka Broker
kafka.bootstrap.servers=localhost:9092

# Outgoing: REST -> Topic 'orders'
mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=ORDERS
mp.messaging.outgoing.orders-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Incoming: Topic 'orders' -> Processor
mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=ORDERS

# DLQ Configuration
mp.messaging.incoming.orders-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.orders-in.dead-letter-queue.topic=ORDERS-DLQ

# Outgoing: Processor -> Topic 'orders-processed'
mp.messaging.outgoing.orders-processed.connector=smallrye-kafka
mp.messaging.outgoing.orders-processed.topic=ORDERS-PROCESSED
mp.messaging.outgoing.orders-processed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
